name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: bitcoin build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: bitcoin/
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/base-nodes:bitcoin-latest
