name: CI - Litecoin

on:
  push:
    branches: [ main ]
    paths:
      - litecoin/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set tag
      id: vars
      run: echo "tag=$(cat litecoin/Dockerfile | grep 'ENV CRYPTO_VERSION' | cut -d '=' -f2)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: litecoin build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: litecoin/
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/base-nodes:litecoin-${{ steps.vars.outputs.tag }} , ${{ secrets.DOCKERHUB_USER }}/base-nodes:bitcoin-latest
