name: CI - Ethereum

on:
  push:
    branches: [ main ]
    paths:
      - ethereum/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set tag
      id: vars
      run: echo "tag=$(cat ethereum/Dockerfile | grep 'ENV CRYPTO_VERSION' | cut -d '=' -f2)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: ethereum build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ethereum/
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/base-nodes:ethereum-${{ steps.vars.outputs.tag }} , ${{ secrets.DOCKERHUB_USER }}/base-nodes:ethereum-latest
