name: CI - Dogecoin

on:
  push:
    branches: [ main ]
    paths:
      - dogecoin/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set tag
      id: vars
      run: echo "tag=$(cat dogecoin/Dockerfile | grep 'ENV CRYPTO_VERSION' | cut -d '=' -f2)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: dogecoin build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: dogecoin/
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          CRYPTO_ARCH=${{ matrix.arch }}
        tags: |
          ${{ secrets.DOCKERHUB_USER }}/base-nodes:dogecoin-${{ steps.vars.outputs.tag }}
          ${{ secrets.DOCKERHUB_USER }}/base-nodes:dogecoin-latest
      strategy:
        matrix:
          arch: [aarch64, x86_64]


